/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f407xx_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void delay3s(void) {
	for (volatile uint32_t i=0; i < 3333333U; i++);
}

int main(void)
{
	GPIO_Handle_t orange_led = {
		GPIOD,
		{
			GPIO_PIN_NO_13,
			GPIO_MODE_OUT,
			GPIO_SPEED_LOW,
			GPIO_NO_PUPD,
			GPIO_OP_TYPE_PP
		}
	};

	GPIO_Handle_t green_led = {
		GPIOD,
		{
			GPIO_PIN_NO_12,
			GPIO_MODE_OUT,
			GPIO_SPEED_LOW,
			GPIO_NO_PUPD,
			GPIO_OP_TYPE_PP
		}
	};

	GPIO_Handle_t blue_led = {
		GPIOD,
		{
			GPIO_PIN_NO_15,
			GPIO_MODE_OUT,
			GPIO_SPEED_LOW,
			GPIO_NO_PUPD,
			GPIO_OP_TYPE_PP
		}
	};

	GPIO_Handle_t red_led = {
		GPIOD,
		{
			GPIO_PIN_NO_14,
			GPIO_MODE_OUT,
			GPIO_SPEED_LOW,
			GPIO_NO_PUPD,
			GPIO_OP_TYPE_PP
		}
	};


	GPIO_Init(&orange_led);
	GPIO_Init(&green_led);
	GPIO_Init(&blue_led);
	GPIO_Init(&red_led);

	for(;;) {
		GPIO_WriteToOutputPin(&red_led, 1);
		delay3s();
		GPIO_WriteToOutputPin(&red_led, 0);
		GPIO_WriteToOutputPin(&green_led, 1);
		delay3s();
		GPIO_WriteToOutputPin(&green_led, 0);
		GPIO_WriteToOutputPin(&orange_led, 1);
		delay3s();
		GPIO_WriteToOutputPin(&orange_led, 0);
	}
}
